use_frameworks!

platform :ios, '9.0'

inhibit_all_warnings!

target 'AppMonitor_Example' do
  pod 'AppMonitor', :path => '../'

  target 'AppMonitor_Tests' do
    inherit! :search_paths

    
  end
end
